# Generated by Django 2.1.3 on 2019-04-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='data_espedicao_rg',
            new_name='data_expedicao_rg',
        ),
    ]
