# Generated by Django 2.1.3 on 2019-01-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['name'], 'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
    ]
