# Generated by Django 2.1.3 on 2019-04-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20190401_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosdevisitas',
            name='cpf',
        ),
        migrations.AddField(
            model_name='pontosdevisitas',
            name='cpf_cnpj',
            field=models.CharField(default='', max_length=14, verbose_name='CPF:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorista',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apelido:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='bairro',
            field=models.CharField(max_length=40, verbose_name='Bairro:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cidade',
            field=models.CharField(max_length=30, verbose_name='Cidade:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='contato1',
            field=models.CharField(blank=True, max_length=11, verbose_name='Contato:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='contato2',
            field=models.CharField(blank=True, max_length=11, verbose_name='Contato adicional:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='data_expedicao_rg',
            field=models.DateTimeField(verbose_name='Data de expedição do RG:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='emissao_cnh',
            field=models.DateTimeField(verbose_name='Data de emissão da CNH:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nascimento',
            field=models.DateTimeField(verbose_name='Data de nascimento:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='num_cnh',
            field=models.CharField(max_length=11, verbose_name='Número de registro:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Código do motorista:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], max_length=7, verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='uf',
            field=models.CharField(choices=[('PI', 'PI'), ('MA', 'MA'), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('ES', 'ES'), ('CE', 'CE'), ('GO', 'GO'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='validade_habilitacao',
            field=models.DateTimeField(verbose_name='Validade da habilitação:'),
        ),
    ]
