# Generated by Django 2.1.3 on 2019-01-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190106_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('rg_identidade', models.IntegerField(verbose_name='RG')),
                ('CPF', models.IntegerField(verbose_name='CPF')),
                ('num_registro', models.IntegerField(verbose_name='Número de registro')),
                ('categoria_habilitacao', models.CharField(max_length=2, verbose_name='Categoria')),
                ('validade_habilitacao', models.DateTimeField(verbose_name='Validade da habilitação')),
                ('start_data', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cadastro/images/motoristas', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cadastro atualizado em')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='about',
            field=models.TextField(blank=True, verbose_name='Observações da Frota'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='slug',
            field=models.SlugField(verbose_name='Código do carro'),
        ),
    ]
