# Generated by Django 2.1.3 on 2019-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190414_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['nome', 'apelido', 'rg', 'data_expedicao_rg', 'cpf', 'nascimento', 'codigo', 'num_cnh', 'emissao_cnh', 'validade_habilitacao', 'categoria', 'endereco', 'complemento', 'bairro', 'cep', 'cidade', 'uf', 'contato1', 'contato2', 'status'], 'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='about',
            field=models.TextField(blank=True, verbose_name='Observações da Frota:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='slug',
            field=models.SlugField(verbose_name='Código do carro:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='start_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='categoria',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Categoria:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='codigo',
            field=models.CharField(max_length=4, verbose_name='Código:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='complemento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Cadastrado em;'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='data_expedicao_rg',
            field=models.DateField(verbose_name='Data de expedição do RG:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='emissao_cnh',
            field=models.DateField(verbose_name='Data de emissão da CNH:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='endereco',
            field=models.CharField(max_length=120, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nascimento',
            field=models.DateField(verbose_name='Data de nascimento:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Cadastro atualizado em:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='validade_habilitacao',
            field=models.DateField(verbose_name='Validade da habilitação:'),
        ),
    ]
