# Generated by Django 2.1.3 on 2019-04-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20190428_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em;'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cadastro atualizado em:'),
        ),
    ]
