# Generated by Django 2.1.3 on 2019-04-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20190428_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='data_expedicao_rg',
            field=models.DateTimeField(verbose_name='Data de expedição do RG:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='emissao_cnh',
            field=models.DateTimeField(verbose_name='Data de emissão da CNH:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nascimento',
            field=models.DateTimeField(verbose_name='Data de nascimento:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='validade_habilitacao',
            field=models.DateTimeField(verbose_name='Validade da habilitação:'),
        ),
    ]
