# Generated by Django 2.1.3 on 2019-02-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20190108_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('codigo', models.CharField(max_length=4, verbose_name='Código do automóvel')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['modelo'],
            },
        ),
    ]
