# Generated by Django 2.1.3 on 2019-02-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_carros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zona', models.CharField(max_length=1, verbose_name='Id')),
                ('zona', models.CharField(max_length=10, verbose_name='Nome da zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['id_zona'],
            },
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='image',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='image',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='validade_habilitacao',
            field=models.DateTimeField(blank=True, verbose_name='Validade da habilitação'),
        ),
    ]
