# Generated by Django 2.1.3 on 2019-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20190227_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço:')),
                ('complemento', models.CharField(max_length=120, verbose_name='Complemento:')),
                ('bairro', models.CharField(max_length=40, verbose_name='Bairro:')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP:')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['bairro'],
            },
        ),
    ]
