# Generated by Django 2.1.3 on 2019-03-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_enderecos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enderecos',
            new_name='PontosDeVisita',
        ),
        migrations.AlterModelOptions(
            name='pontosdevisita',
            options={'ordering': ['bairro'], 'verbose_name': 'Ponto de visita', 'verbose_name_plural': 'Pontos de visitas'},
        ),
    ]
