# Generated by Django 2.1.3 on 2019-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20190311_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosdevisitas',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='pontosdevisitas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pontosdevisitas',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF:'),
        ),
    ]
