# Generated by Django 2.1.3 on 2019-03-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20190315_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosdevisitas',
            name='uf',
            field=models.CharField(choices=[('PI', 'Piauí'), ('MA', 'Maranhão')], max_length=2, verbose_name='UF:'),
        ),
    ]
