# Generated by Django 2.1.3 on 2019-03-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_auto_20190315_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosdevisitas',
            name='cep1',
            field=models.CharField(default='', max_length=5, verbose_name='CEP:'),
        ),
        migrations.AddField(
            model_name='pontosdevisitas',
            name='cep2',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='pontosdevisitas',
            name='uf',
            field=models.CharField(choices=[('PI', 'PI'), ('MA', 'MA'), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('ES', 'ES'), ('CE', 'CE'), ('GO', 'GO'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF:'),
        ),
        migrations.AlterField(
            model_name='zonas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
