# Generated by Django 2.1.3 on 2019-03-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_auto_20190320_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosdevisitas',
            name='cep1',
        ),
        migrations.RemoveField(
            model_name='pontosdevisitas',
            name='cep2',
        ),
    ]
